# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
