# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 08:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serials', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serialwatching',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watching', to=settings.AUTH_USER_MODEL),
        ),
    ]
